name: cobras
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<3.13
  - pandas>=2.0
  - numpy
  - matplotlib
  - plotly
  - networkx
  - pyomo
  - pandapower
  - openpyxl
  - ipopt
  - pytest
  - pyyaml
  - tqdm
  - pip
  - mosek
